import type { Node, Edge } from '@xyflow/react'
import type { PortDef, Category } from './types'

export interface ParamSchemaDef {
  name: string
  type: 'float' | 'int' | 'bool' | 'enum' | 'text'
  min?: number
  max?: number
  default: unknown
  description?: string
  enumValues?: string[]
}

/** Serialized node definition that travels with a graph (for compound/custom nodes) */
export interface SerializedNodeDef {
  type: string
  label: string
  category: Category
  inputs: PortDef[]
  outputs: PortDef[]
  dataFields?: { name: string; type: 'number' | 'string' | 'color'; default: unknown; label?: string; min?: number; max?: number }[]
  evaluateSource: string // function body as string
}

export interface UserPatternGraph {
  id: string
  name: string
  description: string
  nodes: Node[]
  edges: Edge[]
  defaultParams: Record<string, unknown>
  parameterSchema?: ParamSchemaDef[]
  defaultCameraDistance: number
  readOnly?: boolean
  builtinVersion?: number
  customNodeDefs?: SerializedNodeDef[]
  createdAt: string
  updatedAt: string
}

const STORAGE_KEY = 'threelab_user_patterns'

// Built-in graphs generated by the factory — populated at startup
let builtinGraphs: UserPatternGraph[] = []

export function setBuiltinGraphs(graphs: UserPatternGraph[]) {
  builtinGraphs = graphs
}

export function getBuiltinGraphs(): UserPatternGraph[] {
  return builtinGraphs
}

export function loadUserPatterns(): UserPatternGraph[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    const userPatterns: UserPatternGraph[] = raw ? JSON.parse(raw) : []

    // Merge built-in graphs: always present, never editable, auto-updated
    const merged: UserPatternGraph[] = [...builtinGraphs]
    // IDs of legacy example patterns that should no longer appear
    const legacyIds = new Set(['example_lissajous'])
    for (const up of userPatterns) {
      // Skip any stale built-in that got saved to localStorage
      if (builtinGraphs.some((b) => b.id === up.id)) continue
      // Skip legacy example patterns
      if (legacyIds.has(up.id)) continue
      merged.push(up)
    }
    return merged
  } catch {
    return [...builtinGraphs]
  }
}

/** Load only user-created (non-builtin) patterns from localStorage */
export function loadUserOnlyPatterns(): UserPatternGraph[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    const patterns: UserPatternGraph[] = raw ? JSON.parse(raw) : []
    return patterns.filter((p) => !builtinGraphs.some((b) => b.id === p.id))
  } catch {
    return []
  }
}

export function saveUserPatterns(patterns: UserPatternGraph[]) {
  // Never persist built-in graphs to localStorage
  const userOnly = patterns.filter((p) => !p.readOnly)
  localStorage.setItem(STORAGE_KEY, JSON.stringify(userOnly))
}

export function saveUserPattern(pattern: UserPatternGraph) {
  if (pattern.readOnly) return // never save built-ins
  const patterns = loadUserOnlyPatterns()
  const idx = patterns.findIndex((p) => p.id === pattern.id)
  if (idx >= 0) {
    patterns[idx] = pattern
  } else {
    patterns.push(pattern)
  }
  localStorage.setItem(STORAGE_KEY, JSON.stringify(patterns))
}

export function deleteUserPattern(id: string) {
  // Cannot delete built-in patterns
  if (builtinGraphs.some((b) => b.id === id)) return
  const patterns = loadUserOnlyPatterns().filter((p) => p.id !== id)
  localStorage.setItem(STORAGE_KEY, JSON.stringify(patterns))
}

export function generatePatternId(): string {
  return 'up_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6)
}
